name: API Tests (Postman/Newman)

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  newman:
    runs-on: ubuntu-latest
    steps:
      # 1. Baixa o código
      - uses: actions/checkout@v4

      # 2. Instala Node.js
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # 3. Instala o Newman e o Reporter HTML
      - name: Install Newman
        run: npm install -g newman newman-reporter-htmlextra

      # 4. Roda os testes injetando o Token Seguro
      - name: Run Postman Collection
        run: |
          newman run "tests/api/GoRest_CRUD.postman_collection.json" \
          -e "tests/api/GoRest_Env.postman_environment.json" \
          --env-var "token=${{ secrets.GOREST_TOKEN }}" \
          --reporters cli,htmlextra --reporter-htmlextra-export newman-report.html

      # 5. Salva o Relatório HTML como Artefato
      - name: Upload Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: newman-api-report
          path: newman-report.html
          retention-days: 30